### ISSUE TITLE
infoCriteria with multiple models

### ISSUE THREAD

**Issue by kwstat** [briencj/asremlPlus#2]
It would be nice if this function would accept multiple objects, similar to the AIC function.  For example:

```
R> AIC(mm1,mm2)
    df      AIC
mm1  3 46708.52
mm2  4 46654.05
```

**Comment by briencj** [comment]
I can see that such functionality would be convenient for users. I have added to my list of future enhancements and will work on it when I get a chance. Cheers, Chris.

**Comment by briencj** [comment]
I have now expanded the facilities in asremlPlus for information criteria.

Multiple objects can be handled via something like infoCriteria(list(mm1 = mm1, mm2 = mm2)).

However, there is more as is described in the vignette Wheat.infoCriteria available from here or in R via vignette("Wheat.inforCriteria", package = "asremlPlus").

Cheers, Chris
