### ISSUE TITLE
asremlPlus stack usage error

### ISSUE THREAD

**Issue by jahneldardavik** [briencj/asremlPlus#4]
Is this related to asremlPlus?
"
current.asr <- lm
> current.asrt <- as.asrtests(current.asr,NULL,NULL)
Error: C stack usage  15922800 is too close to the limit
"

Appreciate feedback.
Thanky you.
jahn

**Comment by briencj** [comment]
Hi Jahn,

I don’t believe so because it is a memory usage issue and memory management is done  by ASReml-R.  There are workspace options in the asreml and asreml.options of ASReml-R for this.

Cheers,

  Chris
