### ISSUE TITLE
issue infoCriteria

### ISSUE THREAD

**Issue by DiannevdS** [briencj/asremlPlus#6]
Hello,

it seems that the function infoCriteria from asremlPlus is not compatible with the new asreml package (4.2.0.257).
I get this error:

infoCriteria(mget(model_objects), IClikelihood = "full")
Error: 'vpc.char' is not an exported object from 'namespace:asreml'

Is it possible to solve this issue?

Regards,
Dianne

**Comment by briencj** [comment]
Hi Dianne,

You are right that the currently available versions of asremPlus are not compatible with asreml 4.2.

I have been working on a compatible version of asremlPlus, there being several changes in asreml 4.2 that require adjustments to asremlPlus. I will put it up next week – it will be asremlPlus 4.4.x. If your need is urgent, I could send you an interim tar.gz or a Windows binary. Let me know if you want me to do that.

Cheers,

  Chris




From: DiannevdS ***@***.***>
Sent: Thursday, July 13, 2023 5:32 PM
To: briencj/asremlPlus ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [briencj/asremlPlus] issue infoCriteria (Issue #6)

CAUTION: External email. Only click on links or open attachments from trusted senders.

________________________________
Hello,

it seems that the function infoCriteria from asremlPlus is not compatible with the new asreml package (4.2.0.257).
I get this error:

infoCriteria(mget(model_objects), IClikelihood = "full")
Error: 'vpc.char' is not an exported object from 'namespace:asreml'

Is it possible to solve this issue?

Regards,
Dianne

**Comment by DiannevdS** [comment]
Hi Chris,

thanks for your quick reply, no worries I can wait for it 'till next week. Great to see you are working on it!

Regards,
Dianne

**Comment by briencj** [comment]
Hi Dianne,

I have now uploaded asremlPlus 4.4.11 to this gitHub repo and to my R packages repo (http://chris.brien.name/rpackages/). This version of asremlPlus is compatible with ASReml-R versions 3.0, 4.1 and 4.2, but not 4.0. However, it has know issues when the Intel MKL libraries are installed in your R installation directory. These issues are being worked on and I hope to have a solution soon. Meanwhile, all works with a plain vanilla R installation.

Good luck with the new version, but set me now if you strike any further problems with asremlPlus.

Cheers,
Chris

**Comment by DiannevdS** [comment]
Hi Chris,

it's working now, thank you so much for this quick solution.

Regards,
Dianne

**Comment by briencj** [comment]
Hi Dianne,

Glad to hear that all is well.

However, it was not a quick solution. I have been working on it, on and off, since the end of last year. I hadn’t released the new version earlier because of issues that remained.

Cheers,

  Chris
